# Generated by Django 4.0.3 on 2022-08-27 15:15

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Commandé'), ('Processed', 'Traité'), ('Shipped', 'Expédié'), ('Delivered', 'Livré')], default='Ordered', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='products/'),
        ),
    ]
