# Generated by Django 4.0.3 on 2022-08-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
