# Generated by Django 4.0.3 on 2022-09-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_product_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categorysub',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_ar',
            field=models.CharField(choices=[('Ordered', 'استقبال'), ('Processed', 'معالجة'), ('Shipped', 'يتم الشحن'), ('Delivered', 'تم الشحن')], default='Ordered', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
