# Generated by Django 4.0.3 on 2022-09-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_category_name_ar_categorysub_name_ar_order_status_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=20),
        ),
    ]
