# Generated by Django 4.0.3 on 2022-09-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
    ]
